### ISSUE TITLE
Resize children to fit smaller monitors

### ISSUE THREAD

**Issue by BradSchoenrock** [BradSchoenrock/WVD-MCSupdate#103]
The MFF computers were shipped with low res monitors which will be deployed with the system. 

Robert worked on this this morning, but when the children are run as stand alone their window sizes still reflect the old aspect ratios while some controls and indicators are off the screen.

**Comment by stillwer** [comment]
Forgot to deal with the "run in child mode". I just resized the panes containing the children. Now should be fixed and changes committed.

**Comment by BradSchoenrock** [comment]
This was a duplicate of #97
