### ISSUE TITLE
Labview + MCS question: monitoring multiple channels and power monitoring assignments

### ISSUE THREAD

**Issue by BradSchoenrock** [BradSchoenrock/WVD-MCSupdate#36]
Scott asked - 

Robert and Brad,

To move forward with alignments, I made a quick program to display all channels simultaneously – gutting the old MCS program (WVDIAL_AMCS_3.0.vi) and just adding a read of the global variable 'AMCS_data'.  The new program (WVDIAL_1_NCAR_MCS.vi) is on the desktop of the DIAL#2 computer.   Just wanted to let you know what that new code was.

Also, I hooked up two analog signals to the MCS so we can test its power meters capability.  Is there code written that can read these values yet?  If so, could it write the data to a global variable?  That would let us easily plug it into the data analysis program for testing purposes.   

Lastly, for the meeting tomorrow afternoon, the goal is to walk through the task list with Dixon and agree on a work plan for the next quarter.  

Thanks

**Comment by BradSchoenrock** [comment]
Hey Scott, 

We have power monitoring set up and are reading it into the software, if you would like it added to a global variable i can do that, just need to know where its being read in and what the format is. 

I will say we need to limit the use of global variables in our design in order to be able to run similar programs simultaneously. Being able to run both the old MCS and the new MCS simultaneously is one example of this where because they are both writing out the same global variable we are unable to run the test that Josh and I would have liked to see. I don't want us to continue down this design path of being unable to test the way we would like. 

Cheers!

Brad Schoenrock

**Comment by sspuler** [comment]
Brad,
Please just add the option to save it as global array then I will write what I need to read it. 
Thanks
Scott

**Comment by BradSchoenrock** [comment]
global variable AMCS_PowerMon added to WVDOpsPanel.vi to send power monitoring information. AMCS_PowerMon was added to AMCS_data.vi as a global and is a 12 element array of U32 ints.

**Comment by BradSchoenrock** [comment]
Need to add user controls to assign power monitoring channels from MCS to appropriate signals.
