### ISSUE TITLE
new MFF computer transfer

### ISSUE THREAD

**Issue by BradSchoenrock** [BradSchoenrock/WVD-MCSupdate#39]
Transfer software off of the old Montana State computer to the new MFF computer. This will require old software being uploaded into github first. 

Need Robert's help in compiling all the old software.

**Comment by BradSchoenrock** [comment]
Robert is trying to upload it onto another computer, trying to do so with LabView 2012 32 bit, some drivers are 32 bit and don't currently support 64 bit.

**Comment by BradSchoenrock** [comment]
Current bug seems to require matlab installation, robert is contacting rochelle to get key for a matlab installation.

**Comment by stillwer** [comment]
Installed matlab and worked my way through most of the drivers. Current bug specifies that there are Labview compatibility issues with VISA. I can not reinstall. Next plan is to uninstall the National Instruments Suite and try again with exactly the same versions currently running on the old machine.

**Comment by stillwer** [comment]
Finished porting the software this morning to cuttlefish. Testing it now.

**Comment by stillwer** [comment]
Everything seems to be running and semi-happy so I think you can call the transfer finished. If more issues pop up, I wouldn't think they would fall under this any more.
