### ISSUE TITLE
MCR analog measurements are being unpacked incorrectly

### ISSUE THREAD

**Issue by stillwer** [BradSchoenrock/WVD-MCSupdate#42]
The analog return for the MCS is composed of 8 bytes. That is 32 bits, or 8 hex values. As far as I can tell,  the current labview code takes this whole number and converts it to a decimal value and returns that value as the power. Again, as far as I can tell, the first hex byte seems to indicate the channel number. As such, the power values read off of demuxing channel 1 are biased very high. Seems to be that we need to remove the status bytes from the data bytes when converting.

**Comment by BradSchoenrock** [comment]
Resolved in most recent commit.

**Comment by BradSchoenrock** [comment]
Upon testing the fix pushed did not resolve this issue, continuing to look into it.
