### ISSUE TITLE
Add laser locking/etalon routines to template.

### ISSUE THREAD

**Issue by BradSchoenrock** [BradSchoenrock/WVD-MCSupdate#51]
Start with simple replication of current functionality. This will be a longer task alongside MCS controls.

**Comment by stillwer** [comment]
Testing now. Seems to be stable over a few hour time frame. Note that the temperature increase happens much faster than temperature decrease.

**Comment by BradSchoenrock** [comment]
Two things, 

one, robert was committing those changes while i was logged into DIAL2, so he will have more context on those changes from yesterday if needed. 

two, laser locking is in place and so this issue is closed. Any bugs or follow up changes can be added as a new issue.
