### ISSUE TITLE
Container - Global File Paths appending to array

### ISSUE THREAD

**Issue by BradSchoenrock** [BradSchoenrock/WVD-MCSupdate#69]
On startup the global file paths should instantiate an empty array and then fill it, instead of appending to the already existing array and building the array up over time.

**Comment by BradSchoenrock** [comment]
Global file paths are not being filled from Containers configure file. 

When running as standalone should be filled from child's configure file.

**Comment by stillwer** [comment]
Can now be done with a combination of Init_GlobalFilePaths.vi and Init_UpdateGlobalFilePaths.vi. Both are found in the shared resources library.
